services:
  mysql:
    image: mysql:8.0
    container_name: pet-app-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: fpdlswj365
      MYSQL_DATABASE: memberdb
      MYSQL_USER: sunjae
      MYSQL_PASSWORD: fpdlswj365
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-pfpdlswj365"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: pet-app-redis
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    image: eclipse-temurin:17-jdk
    container_name: pet-app
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    working_dir: /app
    volumes:
      - ./build/libs/PetApp-0.0.1-SNAPSHOT.jar:/app/app.jar:ro
    command: ["java", "-jar", "/app/app.jar"]
    environment:
      PASSWORD : titvhgisbkbzrgcw
      EMAIL : chltjswo789@gmail.com
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/memberdb?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: sunjae
      SPRING_DATASOURCE_PASSWORD: fpdlswj365
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: "6379"
      SPRING_DATA_MONGODB_URI: mongodb+srv://chltjswo:fpdlswj365@mycluster.zzoydp8.mongodb.net/chat?retryWrites=true&w=majority&appName=myCluster
      TZ: Asia/Seoul
    ports:
      - "8080:8080"

volumes:
  mysql-data:
  redis-data:
