services:

  app:
    image: sunjaegood/pet-community:dev
    container_name: pet-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
      es:
        condition: service_healthy
    environment:
      TZ: Asia/Seoul
      SPRING_PROFILES_ACTIVE: dev


  mongodb:
    image: mongo:latest
    container_name: pet-app-mongo
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 10


  redis:
    image: redis:7-alpine
    container_name: pet-app-redis
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 10

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.18
    container_name: pet-app-es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
    volumes:
      - es-data:/usr/share/elasticsearch/data
    healthcheck:
      test: [ "CMD-SHELL", "curl -fs http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=5s >/dev/null || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 30s

  rabbitmq:
    image: rabbitmq:3-management
    container_name: pet-app-rabbitmq
    ports:
      - "15672:15672"# 관리 UI 포트
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE} # 클러스터링 시 동일한 값으로 설정
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
      interval: 10s
      timeout: 5s
      retries: 10

  debezium:
    env_file: # 환경변수 파일을 사용하여 설정값을 관리할 수 있도록 env_file 옵션 추가
      - .env
    image: quay.io/debezium/server:3.4
    container_name: pet-app-debezium
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./debezium/config:/debezium/config
      - ./debezium/data:/debezium/data

volumes:
  mongo-data:
  redis-data:
  es-data:
  rabbitmq-data:


