services:
  nginx:
    image: nginx:latest
    container_name: pet-app-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - es01
      - es02
      - es03

  mysql:
    image: mysql:8.0
    container_name: pet-app-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-time-zone=Asia/Seoul
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-p${MYSQL_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 10

  mongodb:
    image: mongo:latest
    container_name: pet-app-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: pet-app-redis
    restart: always
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 10

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.18
    container_name: pet-app-es01
    environment:
      - node.name=es01
      - cluster.name=pet-cluster
      - discovery.seed_hosts=es02,es03 #재배포시 다른 노드들도 추가해줘야함.
      - cluster.initial_master_nodes=es01,es02,es03 # 초기 마스터 노드 설정, 재배포시 노드 추가해서 초기 마스터노드가 자기뿐만 아닌 클러스터에 있는 모든 노드를 넣고 재배포해야함.
      - xpack.security.enabled=false #비번 없이 접속하기 위해 false로 설정
      - ES_JAVA_OPTS=-Xms256m -Xmx256m #힙 메모리 설정 es는 jvm 기반이라 메모리 설정 필요
    ports:
      - "9200:9200"
    volumes:
      - es-data01:/usr/share/elasticsearch/data

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.18
    container_name: pet-app-es02
    environment:
      - node.name=es02
      - cluster.name=pet-cluster
      - discovery.seed_hosts=es01,es03 # 클러스터 내 다른 노드들 설정 부트 당시 어느 노드로가야하는지
      - cluster.initial_master_nodes=es01 #운영중 노드 추가이기 때문에 초기 노드는 그대로 설정
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
    ports:
      - "9201:9200"
    volumes:
      - es-data02:/usr/share/elasticsearch/data


  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.18
    container_name: pet-app-es03
    environment:
      - node.name=es03
      - cluster.name=pet-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
    ports:
      - "9202:9200"
    volumes:
      - es-data03:/usr/share/elasticsearch/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: pet-app-rabbitmq
    restart: always
    ports:
      - "5672:5672"# RabbitMQ 서버 포트
      - "15672:15672"# 관리 UI 포트
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE} # 클러스터링 시 동일한 값으로 설정
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
      interval: 10s
      timeout: 5s
      retries: 10

  debezium:
    image: quay.io/debezium/server:3.4
    container_name: pet-app-debezium
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./debezium/conf:/debezium/conf
      - ./debezium/data:/debezium/data
    environment:
      - DEBEZIUM_SINK_TYPE=rabbitmq
      - DEBEZIUM_SINK_RABBITMQ_CONNECTION_HOST=rabbitmq
      - DEBEZIUM_SINK_RABBITMQ_CONNECTION_PORT=${RABBITMQ_PORT}
      - DEBEZIUM_SINK_RABBITMQ_CONNECTION_USERNAME=${RABBITMQ_USERNAME}
      - DEBEZIUM_SINK_RABBITMQ_CONNECTION_PASSWORD=${RABBITMQ_PASSWORD}
      - DEBEZIUM_SINK_RABBITMQ_EXCHANGE=ex.main
      - DEBEZIUM_SINK_RABBITMQ_ROUTINGKEY_SOURCE=key #key 값을 라우팅 키로 설정

      - DEBEZIUM_FORMAT_KEY=simplestring #schema 없이 단순 문자열로 key를 전달하기 위한 설정
      - DEBEZIUM_SOURCE_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - DEBEZIUM_SOURCE_VALUE_CONVERTER_SCHEMAS_ENABLE=false

      # smt 설정
      - DEBEZIUM_SOURCE_TRANSFORMS=outbox #outbox라는 이름으로 smt 설정
      - DEBEZIUM_SOURCE_TRANSFORMS_OUTBOX_TYPE=io.debezium.transforms.outbox.EventRouter #공식 outbox smt 사용
      - DEBEZIUM_SOURCE_TRANSFORMS_OUTBOX_TABLE_FIELD_EVENT_ID=id #id 필드를 이벤트 id로 지정
      - DEBEZIUM_SOURCE_TRANSFORMS_OUTBOX_TABLE_FIELD_EVENT_KEY=routing_key #routingKey 필드를 이벤트 키로 지정
      - DEBEZIUM_SOURCE_TRANSFORMS_OUTBOX_TABLE_FIELD_EVENT_PAYLOAD=payload #실제 전달해야 할 데이터
      - DEBEZIUM_SOURCE_TRANSFORMS_OUTBOX_ROUTE_BY_FIELD=routing_key #라우팅 키로 사용할 필드 지정
      - DEBEZIUM_SOURCE_TRANSFORMS_OUTBOX_TABLE_FIELDS_ADDITIONAL_PLACEMENT=id:envelope #id필드 추가(envlope: 부가 정보를 추가)

      # mysql 설정
      - DEBEZIUM_SOURCE_CONNECTOR_CLASS=io.debezium.connector.mysql.MySqlConnector
      - DEBEZIUM_SOURCE_OFFSET_STORAGE=org.apache.kafka.connect.storage.FileOffsetBackingStore #오프셋 정보를 파일로 저장하기 위한 설정
      - DEBEZIUM_SOURCE_OFFSET_STORAGE_FILE_FILENAME=/debezium/data/offsets.dat #오프셋 정보를 저장할 파일 경로
      - DEBEZIUM_SOURCE_DATABASE_HOSTNAME=mysql
      - DEBEZIUM_SOURCE_DATABASE_PORT=${MYSQL_PORT}
      - DEBEZIUM_SOURCE_DATABASE_USER=${MYSQL_USER}
      - DEBEZIUM_SOURCE_DATABASE_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DEBEZIUM_SOURCE_DATABASE_SERVER_ID=${DEBEZIUM_SOURCE_DATABASE_SERVER_ID}
      - DEBEZIUM_SOURCE_TABLE_INCLUDE_LIST=${MYSQL_DATABASE}.outbox_event #모니터링할 테이블 설정, outbox_event 테이블의 변경사항을 모니터링
      - DEBEZIUM_SOURCE_TOPIC_PREFIX=outbox #토픽 접두사 설정

      # 성능 설정
      - DEBEZIUM_SOURCE_MAX_BATCH_SIZE=1000 #배치 사이즈 설정, 한번에 최대 1000개의 이벤트를 처리(기본값은 2048)
      - DEBEZIUM_SOURCE_POLL_INTERVAL_MS=500 #0.5초마다
      # 에러 처리
      - DEBEZIUM_SOURCE_EVENT_PROCESSING_FAILURE_HANDLING_MODE=fail #에러 발생 시 debeizium 서버 중단


      - DEBEZIUM_SOURCE_SCHEMA_HISTORY_INTERNAL=io.debezium.storage.file.history.FileSchemaHistory #스키마 변경 이력을 파일로 저장하기 위한 설정
      - DEBEZIUM_SOURCE_SCHEMA_HISTORY_INTERNAL_FILE_FILENAME=/debezium/data/history.dat #스키마 변경 이력을 저장할 파일 경로
      - DEBEZIUM_SOURCE_INCLUDE_SCHEMA_CHANGES=false #스키마 변경 이벤트를 토픽에 포함하지 않도록 설정, 스키마 변경 이벤트는 일반적으로 필요하지 않으므로 false로 설정하여 불필요한 이벤트 생성을 방지
      - DEBEZIUM_SOURCE_SNAPSHOT_MODE=initial #스냅샷 모드

volumes:
  mysql-data:
  mongo-data:
  redis-data:
  uploads-data:
  es-data01:
  es-data02:
  es-data03:
  rabbitmq-data:


