services:

  mongodb:
    image: mongo:latest
    container_name: pet-app-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db


  redis:
    image: redis:7-alpine
    container_name: pet-app-redis
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis-data:/data

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.18
    container_name: pet-app-es
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false #비번 없이 접속하기 위해 false로 설정
      - ES_JAVA_OPTS=-Xms256m -Xmx256m #힙 메모리 설정 es는 jvm 기반이라 메모리 설정 필요
    volumes:
      - es-data:/usr/share/elasticsearch/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: pet-app-rabbitmq
    ports:
      - "5672:5672" # AMQP 포트
      - "15672:15672"# 관리 UI 포트
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE} # 클러스터링 시 동일한 값으로 설정
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  debezium:
    env_file: # 환경변수 파일을 사용하여 설정값을 관리할 수 있도록 env_file 옵션 추가
      - .env.dev
    image: quay.io/debezium/server:3.4
    container_name: pet-app-debezium
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./debezium/config:/debezium/config
      - ./debezium/data:/debezium/data

volumes:
  mongo-data:
  redis-data:
  es-data:
  rabbitmq-data:


