jwt:
  accessKey: ${ACCESS_KEY}
  refreshKey: ${REFRESH_KEY}
spring:
  elasticsearch:
    uris: http://localhost:80
  datasource:
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      connection-timeout: 3000
      validation-timeout: 1000
      leak-detection-threshold: 5000
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE}?useUnicode=true&serverTimezone=Asia/Seoul
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_EMAIL}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

  rabbitmq:
    addresses: localhost:5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    listener:
      simple:
        prefetch: 10
        acknowledge-mode: auto
        concurrency: 4
        max-concurrency: 8
    publisher-confirm-type: correlated #해당 메시지 전송 확인

  data:
    mongodb:
      uri: ${MONGO_URI}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
    redis:
      repositories:
        enabled: false

  redis:
    host: 127.0.0.1
    port: 6379

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  cloud:
    aws:
      credentials:
        access-key: ${AWS_IAM_ACCESS_KEY}
        secret-key: ${AWS_IAM_SECRET_KEY}
      region:
        static: ${AWS_S3_REGION}

  # Elasticsearch Reactive Repositories 오토컨피그 비활성화
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.elasticsearch.ReactiveElasticsearchRepositoriesAutoConfiguration

mail:
  provider: smtp

logging:
  level:
    org.elasticsearch.client: TRACE

aws:
  s3:
    bucket: ${AWS_S3_BUCKET}
  cloudfront:
    domain: ${AWS_CLOUD_FRONT}

management:
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
    enable:
      all: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  health:
    mongo:
      enabled: false

server:
  address: 0.0.0.0
  port: 8080
