jwt:
  accessKey: ${ACCESS_KEY:12345678901234567890123456789012}
  refreshKey: ${REFRESH_KEY:12345678901234567890123456789012}
spring:
  elasticsearch:
    uris: ${ELASTICSEARCH_URI:http://localhost:9200}
  datasource:
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      connection-timeout: 3000
      validation-timeout: 1000
      leak-detection-threshold: 5000
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/pet_community?useUnicode=true&serverTimezone=Asia/Seoul}
    username: ${MYSQL_ROOT_USERNAME:root}
    password: ${MYSQL_ROOT_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        show_sql: true
    open-in-view: false

  data:
    redis:
      repositories:
        enabled: false
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY:aws-access-key}
        secret-key: ${AWS_SECRET_KEY:aws-secret-key}
      region:
        static: ${AWS_S3_REGION:ap-northeast-2}

  # Elasticsearch Reactive Repositories 오토컨피그 비활성화
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.elasticsearch.ReactiveElasticsearchRepositoriesAutoConfiguration

springdoc:
  swagger-ui:
    path: /swagger


logging:
  level:
    org.elasticsearch.client: TRACE

storage:
  type: ${STORAGE_TYPE:local}

aws:
  s3:
    bucket: ${AWS_S3_BUCKET:aws-s3-bucket}
  cloudfront:
    domain: ${AWS_CLOUD_FRONT:aws-cloudfront}

server:
  address: 0.0.0.0
  port: 8080
