jwt :
  accessKey : 45124589562312457845134679461312
  refreshKey : 13462356794613462356897946132346
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${PASSWORD}
    properties:
       mail:
        smtp:
          auth: true
          starttls:
            enable: true

  dog:
    profile:
      image:
        upload: /Users/choiseonjae/Desktop/PetApp/profiles
    post:
      image:
        upload: /Users/choiseonjae/Desktop/PetApp/posts
    member:
      image:
        upload: /Users/choiseonjae/Desktop/PetApp/members
  data:
    redis:
      repositories:
        enabled: false
    mongodb:
      uri: ${MONGO_URI}

server:
  address: 0.0.0.0
  port: 8080
